# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1
project_name: gosh

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - id: gosh
    main: ./cmd/gosh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gosh
    # alternative_names:
    #   - gosh@{{ .Version }}
    #   - gosh@{{ .Major }}
    #   - gosh@{{ .Major }}.{{ .Minor }}
    url_template: "https://github.com/yogin/gosh/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/yogin/gosh"
    description: "CLI to list and access cloud instances"
    license: "MIT"
    repository:
      owner: yogin
      name: homebrew-tap
      branch: "{{ .ProjectName }}/{{ .Version }}"
      pull_request:
        enabled: true
        draft: true
        base:
          branch: master
      git:
        url: "ssh://git@github.com:yogin/homebrew-tap.git"
